### PR TITLE
Misplaced dependency fix.

### PR DESCRIPTION
**Pull request by azusa0127**
Nice little tool, though `strip-ansi` is a necessary dependency for it to run - previously placed in devDep.

### CODE REVIEW

**Comment by CodeLenny** [comment]
Whoops!  Aren't those the hardest to catch in CI.  Thanks for the PR!  However - I normally bump the version using `npm update`, which will change `version` in `package.json`, and add a `git tag`, which GitHub will use to create the list of [releases](https://github.com/CodeLenny/Promise.bar/releases), but `npm update` will yell if `package.json` has already been changed.

I'm feeling lazy, any chance you could make the 1 line modification to revert the `version` in `package.json`?  Otherwise I'll get around to it tomorrow :)

Again, thanks for contributing!  Are you using `Promise.bar` for anything yet?

**Comment by azusa0127** [comment]
Sure I could do that, but you'd need to update/publish the package any way - so feel free to move the line and update it :).

I'm using `promise.bar`  in a private project that makes thousands of concurrent requests(with [limiter](https://www.npmjs.com/package/better-limiter) and multiple retries) in promises --  `promise.bar` fits in the scene perfectly :p, I'm glad I found it the second before I'm writing one.

**Comment by CodeLenny** [comment]
My apologies, I was definitely a little tired when I responded.  It's easiest to just merge, revert version number, bump it with `npm version`, then publish :)  I'll go ahead and do that now.

Sounds like a great use for the library!  Please let me know if there are any missing or unclear docs, or features that are missing!  Can't guarantee that I'll have time to resolve them, but I'd love to keep track of the issues.

**Comment by CodeLenny** [comment]
@azusa0127 Version `0.1.5` has now been published to NPM.  Thanks for helping out with the PR!

**Pull request merged**
